sudo: require
language: cpp
dist: trusty

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz"
    - BOOST_VERSION="1_63_0"

cache:
  directories:
    - ${DEPS_DIR}


matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


# Install dependencies
before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      # create dirs for source and install
      mkdir -p ${DEPS_DIR}/boost${BOOST_VERSION}
      mkdir -p ${DEPS_DIR}/boost
      # download
      travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/boost${BOOST_VERSION}
      pushd ${DEPS_DIR}/boost${BOOST_VERSION}
      # configure and install
      ./bootstrap.sh --prefix=${DEPS_DIR}/boost/ --with-libraries=iostreams,test,filesystem,system,thread
      ./b2 -d0 install
      popd
      if [[ -d ${DEPS_DIR}/boost ]]; then
        CMAKE_OPTIONS+=" -DBOOST_ROOT=${DEPS_DIR}/boost";
        export LD_LIBRARY_PATH=$DEPS_DIR/boost/lib:$LD_LIBRARY_PATH
      fi
    fi

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ${CMAKE_OPTIONS} ..
    - make
    - ctest
